### PR TITLE
Fixed #49

### LINKED ISSUE #49: loggly.log("message", undefined) breaks
Noticed that since November update, loggly.log("message", error) when error=undefined breaks where it shouldn't (I guess).

Offending line: https://github.com/winstonjs/winston-loggly/blob/ff56088b4cf76fd00724ebab3cfe37f2ab66276a/lib/winston-loggly.js#L116

See related issue on Winston: https://github.com/winstonjs/winston/issues/947

Can PR if you confirm.

### PR DESCRIPTION
**Pull request by grantcarthew**

### CODE REVIEW

**Comment by grantcarthew** [comment]
Hey @indexzero and or @jcrugzz can one of you guys merge and publish this please. It is a simple fix.

**Comment by grantcarthew** [comment]
Please guys, this is a very simple fix! @sirgalleto

**Comment by DABH** [comment]
Merged this, will see about pushing a new version to npm.  Sorry for the long delay, thank you for your contribution!

**Comment by nicgordon** [comment]
@DABH could we please get this pushed to npm? Thank you.

**Pull request merged**
