### PR TITLE
Add support for host

### PR DESCRIPTION
**Pull request by chris-rudmin**

### CODE REVIEW

**Comment by adamhadani** [comment]
:+1: 
a bit surprised native support for including a host/ip isn't already available for this integration, absolutely needed in a load-balanced/distributed environment, esp. if underlying 'loggly' node.js library supports this argument already

**Comment by Phylodome** [comment]
:+1:

**Comment by rosshettel** [comment]
:+1: Yeah, this would be great to have!

**Comment by adamhadani** [comment]
@indexzero  anything stopping merging this PR in?

**Comment by srt32** [comment]
:+1:

**Comment by bradfol** [comment]
Hey all, I was tripped up by the README on this. The `host` option does *not* allow a hostname to be sent with the logs. It is actually the destination for the logs to be sent to. 

Setting it to `os.hostname()` as I did will **silently** break communication with Loggly, which is bad.

The default is `logs-01.loggly.com`, and I'm not aware of a use case to change that.
https://github.com/nodejitsu/node-loggly/blob/master/lib/loggly/client.js#L52

I would suggest reverting this, as it is breaks the transport silently. At a minimum, I can submit a PR to correct the README.

**Comment by indexzero** [comment]
@bradfol thanks for finding this. An update to tests with a subsequent PR would be very helpful.

**Comment by chris-rudmin** [comment]
@bradfol @indexzero I misunderstood the purpose of host. Thanks for caching this. I would suggest undoing my PR, as there is not really a good reason to configure this. Apologies for troubles caused.

**Comment by bradfol** [comment]
@indexzero @chris-rudmin Thanks guys. I've opened PR #35 to revert this.

**Pull request merged**
